config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  root to: 'home#top'
  get 'about', to: 'home#about'
  get "search", to: 'hospitals#search'
  post '/homes/guest_sign_in', to: 'home#new_guest'

  resources :members, only: [:show, :edit, :update] do
    resources :events, only: [:edit, :index, :create, :update, :destroy]
  end

  namespace :admin do
    resources :hospitals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :medical_departments, only: [:show, :index, :create, :edit, :update, :destroy]
    resources :consultation_days, only: [:index, :create, :update, :destroy]
  end

  resources :hospitals, only: [:show, :index] do
    resources :hospital_favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:show, :create] do
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :medical_departments, only: [:show, :index]
end

app/models/medical_department.rb
class MedicalDepartment < ApplicationRecord
  has_many :medicals
  has_many :hospitals, through: :medicals

  validates :name, presence: true
  validates :name, length: {maximum: 10}

  def self.search(search)
    MedicalDepartment.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/admin/medical_departments_controller.rb
class Admin::MedicalDepartmentsController < ApplicationController
  def index
    @medical_departments = MedicalDepartment.all
    @medical_department = MedicalDepartment.new
  end

  def edit
    @medical_department = MedicalDepartment.find(params[:id])
  end

  def update
    medical_department = MedicalDepartment.find(params[:id])
    if medical_department.update(medical_department_params)
      redirect_to admin_medical_departments_path
    else
      render "edit"
    end
  end

  def create
    medical_department = MedicalDepartment.new(medical_department_params)
    medical_department.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    medical_department = MedicalDepartment.find(params[:id])
    medical_department.destroy
    redirect_back(fallback_location: admin_hospitals_path)
  end

  private
  def medical_department_params
    params.require(:medical_department).permit(:name)
  end
end

app/controllers/medical_departments_controller.rb
class MedicalDepartmentsController < ApplicationController
  before_action :today_events

  def show
    @medical_department = MedicalDepartment.find(params[:id])
    @hospitals = @medical_department.hospitals
  end

  def index
    @medical_departments = MedicalDepartment.all
  end
end

app/helpers/admin/medical_departments_helper.rb
module Admin::MedicalDepartmentsHelper
end

app/helpers/medical_departments_helper.rb
module MedicalDepartmentsHelper
end

app/views/medical_departments/index.html.erb
<h1>診療科目一覧</h1>
<% @medical_departments.each do |medical_department| %>
  <%= link_to medical_department.name, medical_department_path(medical_department) %>
<% end %>

app/views/medical_departments/show.html.erb
<h1><%= @medical_department.name %>の病院</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th>診療受付時間</th>
    <th>日</th>
    <th>月</th>
    <th>火</th>
    <th>水</th>
    <th>木</th>
    <th>金</th>
    <th>土</th>
    <th></th>
    <th></th>
  </tr>

  <% @hospitals.each do |hospital| %>
    <tr>
      <td><%= link_to hospital.name, hospital_path(hospital) %></td>
      <td><%= hospital.short_message %></td>

      <td>
        <% hospital.medical_departments.each do |medical_department| %>
          <%= medical_department.name %>
        <% end %>
      </td>

      <td>
        <% hospital.consultation_times.each do |consultation_time| %>
          <%= consultation_time.start_hour %>
          <%= consultation_time.start_minute %>
          <%= consultation_time.finish_hour %>
          <%= consultation_time.finish_minute %>
        <% end %>
      </td>

      <% hospital.consultation_days.each do |consultation_day| %>
        <td><%= consultation_day.is_sunday %></td>
        <td><%= consultation_day.is_monday %></td>
        <td><%= consultation_day.is_tuesday %></td>
        <td><%= consultation_day.is_wednesday %></td>
        <td><%= consultation_day.is_thursday %></td>
        <td><%= consultation_day.is_friday %></td>
        <td><%= consultation_day.is_saturday %></td>
      <% end %>

      <td>口コミ<%= link_to hospital.comments.count, hospital_comment_path(hospital.id)%>件</td>
      <td><%= hospital.phone_number %></td>
    </tr>
  <% end %>
</table>