config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  root to: 'home#top'
  get 'about', to: 'home#about'
  get "search", to: 'hospitals#search'
  post '/homes/guest_sign_in', to: 'home#new_guest'

  resources :members, only: [:show, :edit, :update] do
    resources :events, only: [:edit, :index, :create, :update, :destroy]
  end

  namespace :admin do
    resources :hospitals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :medical_departments, only: [:show, :index, :create, :edit, :update, :destroy]
    resources :consultation_days, only: [:index, :create, :update, :destroy]
  end

  resources :hospitals, only: [:show, :index] do
    resources :hospital_favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:show, :create] do
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :medical_departments, only: [:show, :index]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :today_events

  def top
    @medical_departments = MedicalDepartment.all
  end

  def about
  end

  def new_guest
    member = Member.find_or_create_by!(name: 'ゲスト太郎', nickname: 'ゲスト', email: 'guest1@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
    end
    sign_in member
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row about-title">
    <h1>ー 全国の病院をホスnaviで検索できます ー</h1>
  </div>
</div>

<div class="container">
  <div class="row about1">
    <div class="col-md-6 about-img1"></div>
    <div class="col-md-6 about-font">
      <p class="about-font-question">近所にどんな病院があるか分からない？</p>
      <p class="about-font-question1">
        ホスnaviなら地域毎、診療科目別に病院を検索することができます。
        「都道府県」「診療科目」「何でも検索」と、カテゴリごとに分けられます。
        皆様にあった病院をお知らせするのがポイントです。
      </p>
    </div>
  </div>

  <div class="row about2">
    <div class="col-md-6 about-font">
      <p class="about-font-question">評判の良い病院はどこ？</p>
      <p class="about-font-question2">
        ホスnaviなら来院した患者さんのコメント、いいね数を見る事が出来るので患者さんに合った病院を見つける事ができます。
      </p>
    </div>
    <div class="col-md-6 about-img2"></div>
  </div>

  <div class="row about3">
    <div class="col-md-6 about-img3"></div>
    <div class="col-md-6 about-font3">
      ホスnaviは、あなたの医療をサポートします
    </div>
    <div class="about-link_to_font3">
      <%= link_to hospitals_path do %>
        病院検索を始める
      <% end %>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="home-top">
      <div class="home-top-font1">これからの医療をここから</div>
      <div class="home-top-font2">より良い医療をもっと身近に、もっと気軽に</div>
    </div>
  </div>

  <div class="row">
    <div class="home-md">
      <div class="col-md-6 home-md-img">
      </div>
      <div class="col-md-6 home-md-font">
      <div class="home-box">
        <p class="home-titele">診療科目から病院を探す</p>
        </div>
        <table>
          <tr>
            <th class="home-md-th">
              <%= link_to "内科", search_path(search_link_medical_department: "内科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">風邪・発熱・扁桃腺炎・インフルエンザ・腹痛・下痢など</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "小児科", search_path(search_link_medical_department: "小児科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">風邪・発熱・扁桃腺炎・インフルエンザ・おたふくかぜなど</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "皮膚科", search_path(search_link_medical_department: "皮膚科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">アトピー性皮膚炎・かぶれ・蕁麻疹・やけどなど</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "婦人科", search_path(search_link_medical_department: "婦人科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">子宮筋腫・子宮内膜症・性器脱・子宮頸がんなど</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "眼科", search_path(search_link_medical_department: "眼科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">白内障・緑内障・加齢黄斑変性・ドライアイなど</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "耳鼻咽喉科", search_path(search_link_medical_department: "耳鼻咽喉科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">慢性中耳炎・真珠腫性中耳炎・耳硬化症・咽頭炎など</td>
          </tr>

          <tr>
            <th class="home-md-th">
              <%= link_to "整形外科", search_path(search_link_medical_department: "整形外科"), {class: "home-md-link"} %>
            </th>
            <td class="home-md-td">骨折・打撲・捻挫・骨粗鬆症・末梢神経障害など</td>
          </tr>
        </table>
        <%= link_to "すべての診療科目を見る", hospitals_path, {class: "home-md-all_link"} %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="home-area">
      <div class="col-md-6 area-font">
        <div class="home-box">
          <p class="home-titele">都道府県から病院を探す</p>
        </div>
        <table>
          <tr>
            <th class="home-area-th">北海道・東北</th>
            <td class="home-area-td">
              <% ["北海道", "青森", "岩手", "宮城", "秋田", "山形", "福島"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">関東</th>
            <td class="home-area-td">
              <% ["茨城", "栃木", "群馬", "埼玉", "千葉", "東京", "神奈川"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">甲信越・北陸</th>
            <td class="home-area-td">
              <% ["新潟", "富山", "石川", "福井", "山梨", "長野"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">東海</th>
            <td class="home-area-td">
              <% ["岐阜", "静岡", "愛知", "三重"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">近畿</th>
            <td class="home-area-td">
              <% ["滋賀", "京都", "大阪", "兵庫", "奈良", "和歌山"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">中国</th>
            <td class="home-area-td">
              <% ["鳥取", "島根", "岡山", "広島", "山口"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th class="home-area-th">四国</th>
            <td class="home-area-td">
              <% ["徳島", "香川", "愛媛", "高知"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>

          <tr class="aaa">
            <th class="home-area-th">九州・沖縄</th>
            <td class="home-area-td">
              <% ["福岡", "佐賀", "長崎", "熊本", "大分", "宮崎", "鹿児島", "沖縄"].each do |area| %>
                <%= link_to "#{area}", search_path(search_address: "#{area}"), {class: "home-area-link"} %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>

      <div class="col-md-6 area-img">
      </div>
    </div>
  </div>
</div>