config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  root to: 'home#top'
  get 'about', to: 'home#about'
  get "search", to: 'hospitals#search'
  post '/homes/guest_sign_in', to: 'home#new_guest'

  resources :members, only: [:show, :edit, :update] do
    resources :events, only: [:edit, :index, :create, :update, :destroy]
  end

  namespace :admin do
    resources :hospitals, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :medical_departments, only: [:show, :index, :create, :edit, :update, :destroy]
    resources :consultation_days, only: [:index, :create, :update, :destroy]
  end

  resources :hospitals, only: [:show, :index] do
    resources :hospital_favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:show, :create] do
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :medical_departments, only: [:show, :index]
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  validates :name, length: { maximum: 15 }
  validates :nickname, presence: true
  validates :nickname, length: { maximum: 15 }

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :comments
  has_many :favorites
  has_many :hospital_favorites
  has_many :hospitals, through: :hospital_favorites
  has_many :events

  attachment :image

  def already_favorited?(comment)
    self.favorites.exists?(comment_id: comment.id)
  end

  def already_hospital_favorited?(hospital)
    self.hospital_favorites.exists?(hospital_id: hospital.id)
  end

  protected
  def self.find_for_google(auth)
    member = Member.find_by(email: auth.info.email)

    unless member
      member = Member.create!(name: auth.info.name,
                          nickname: auth.info.name,
                             email: auth.info.email,
                          provider: auth.provider,
                          uid:      auth.uid,
                          token:    auth.credentials.token,
                          password: Devise.friendly_token[0, 20])
    end
    member
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!, only: [:show, :edit]
  before_action :today_events

  def show
    @event = Event.new
    @events = current_member.events.all
    @hospital = current_member.hospital_favorites
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to member_path(current_member)
    else
      render "edit"
    end
  end

  private
  def member_params
    params.require(:member).permit(:nickname, :image)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 member-e-form">
      <%= attachment_image_tag @member, :image, fallback: "no_image.jpg", size:"200x160", class: 'member-s-image' %>
      <%= form_with model: @member, local: true do |f| %>
        <%# エラーメッセージ 部分テンプレート化 %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="member-e-form-member-name form-group">
          ユーザー名<%= f.text_field :nickname ,class: "form-control" %>
        </div>
        <%= f.attachment_field :image, placeholder: "画像", class: "member-e-form-attachment-f" %>
        <%= f.submit "登録情報変更",class: "member-edit-submit btn btn-success" %>
      <% end %>
    </div>

    <div class="col-md-4">
    </div>
  </div>
</div>

app/views/members/show.html.erb
<div class="container member-s-container">
  <% if flash[:notice] %>
    <p class="alert alert-success">
      <%= flash[:notice] %>
    </p>
  <% end %>

  <div class="row">
    <div class="col-md-6 hospital-i-index-img">
      <div class="member-s-div-image">
        <div><%= attachment_image_tag current_member, :image, format: 'jpeg', size: "150x150", fallback: "noprofile_image.jpg", class: 'member-s-image' %></div>
        <div><%= current_member.nickname %></div>
      </div>
      <table class="member-s-table">
        <tr>
          <th>名前</th>
          <td><%= current_member.name %></td>
        </tr>
        <tr>
          <th>email</th>
          <td><%= current_member.email.truncate(40) %></td>
        </tr>
      </table>

      <%= form_with model: @event, url: member_events_path(current_member),local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              日付
              <%= f.date_field :start_time, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 member-s-link-event-user">
            <%= link_to member_events_path(current_member), class: "member-s-link-event link_to_color_red" do %>
              診療予約<span class="member-s-link-events">一覧</span>へ
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              タイトル
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 member-s-link-event-user">
            <%= link_to edit_member_path(current_member), class: "member-s-link-user link_to_color_blue" do %>
              ユーザー<span class="member-s-link-users">編集</span>へ
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              メモ
              <%= f.text_area :content, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="member-s-link-favorite">
              <%= link_to hospital_hospital_favorites_path(@hospital), class: "link_to_color_black" do %>
                <div class="member-s-link-hospital">
                  お気に入り<span class="member-s-link-hospitals">病院</span><%= current_member.hospital_favorites.count %>件
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="submit">
          <%= f.submit "登録" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-6 hospital-i-index-img">
      <%= month_calendar events: @events do |date, events| %>
        <%= date.day %>

        <% events.each do |event| %>
          <div>
            <%= link_to event.title.truncate(4), edit_member_event_path(event.member_id, event), {class: "link_to_color_black"} %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>